export default Object.freeze({
  LOG_OUT: 'LOG_OUT',
  MESSAGE_NOTIFICATION: 'MESSAGE_NOTIFICATION',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  KEYCARD: 'KEYCARD',
  REMINDER_REST: 'REMINDER_REST',
  DETAIL_CUSTOMER: 'DETAIL_CUSTOMER',
  PAYMENT_KEEP_PRICE: 'PAYMENT_KEEP_PRICE',
  PAYMENT_AFTER_CHECKOUT: 'PAYMENT_AFTER_CHECKOUT',
  DETAIL_UNCHECKIN: 'DETAIL_UNCHECKIN',
  DETAIL_CHECKIN: 'DETAIL_CHECKIN',
  DETAIL_CHECKOUT: 'DETAIL_CHECKOUT',
  DETAIL_CLEANING: 'DETAIL_CLEANING',
  DETAIL_CLEANED: 'DETAIL_CLEANED',
  DETAIL_REST: 'DETAIL_REST',
  DETAIL_RESERVE: 'DETAIL_RESERVE',
  CHANGEROOM: 'CHANGEROOM'
})
