export default Object.freeze({
  PAYMENT_INSERT_BOOKING: 'PAYMENT_INSERT_BOOKING',
  PAYMENT_INSERT_REST_BOOKING: 'PAYMENT_INSERT_REST_BOOKING',
  PAYMENT_UNCHECKIN: 'PAYMENT_UNCHECKIN',
  PAYMENT_CHECKOUT: 'PAYMENT_CHECKOUT',
  PAYMENT_REST_CHECKOUT: 'PAYMENT_REST_CHECKOUT',
  PAYMENT_EXTRA_PAYMENT: 'PAYMENT_EXTRA_PAYMENT',
  PAYMENT_CHANGE_ROOM: 'PAYMENT_CHANGE_ROOM',
  PAYMENT_ADD_REST: 'PAYMENT_ADD_REST',
  PAYMENT_UPDATE_TOTAL: 'PAYMENT_UPDATE_TOTAL',
  PAYMENT_REST_CARD_DETAIL: 'PAYMENT_REST_CARD_DETAIL'
})
