export default Object.freeze({
  PRICE_INSERT_BOOKING: 'PRICE_INSERT_BOOKING',
  PRICE_INSERT_REST_BOOKING: 'PRICE_INSERT_REST_BOOKING',
  PRICE_CHECKOUT: 'PRICE_CHECKOUT',
  PRICE_REST_CHECKOUT: 'PRICE_REST_CHECKOUT',
  PRICE_EXTRA_PAYMENT: 'PRICE_EXTRA_PAYMENT',
  PRICE_CHANGE_ROOM: 'PRICE_CHANGE_ROOM',
  PRICE_UNCHECKIN: 'PRICE_UNCHECKIN',
  PRICE_ADD_REST: 'PRICE_ADD_REST',
  PRICE_UPDATE_TOTAL: 'PRICE_UPDATE_TOTAL',
  PRICE_REST_CARD_DETAIL: 'PRICE_REST_CARD_DETAIL',
  PRICE_UNCHECKIN_CARD_DETAIL: 'PRICE_UNCHECKIN_CARD_DETAIL',
  PRICE_RESERVE_CARD_DETAIL: 'PRICE_RESERVE_CARD_DETAIL',
  PRICE_CHECKIN_CARD_DETAIL: 'PRICE_CHECKIN_CARD_DETAIL',
  PRICE_ORDER_INFO: 'PRICE_ORDER_INFO',
  PRICE_ORDER_INFO_PAYMENT: 'PRICE_ORDER_INFO_PAYMENT'
})
